# Stage 1: Build the Angular application
FROM node:20 

# Set the working directory inside the container
WORKDIR /front

RUN npm install -g @angular/cli@17

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm i

# Copy the rest of the application code
# COPY . .

# Build the Angular application
# RUN npx ng build -c production 