# Stage 1: Build the Angular application
# FROM httpd:2.4.48
FROM node:20 

SHELL ["/bin/bash", "-c"]

# Set the working directory inside the container
WORKDIR /front


RUN apt-get update
RUN apt-get install -y pkg-config make gcc gdb lcov valgrind vim curl iputils-ping wget
RUN apt-get install -y autoconf automake libtool
RUN apt-get install -y libssl-dev libjansson-dev libcurl4-openssl-dev check
RUN apt-get install -y libpcre3-dev zlib1g-dev libcjose0 libcjose-dev
RUN apt-get install -y libapache2-mod-security2

RUN apt-get update 
RUN curl -sL https://deb.nodesource.com/setup_20.x | bash - >> output.log 2>&1
RUN apt-get install -y nodejs >> output.log 2>&1
RUN npm install -g @angular/cli@17

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm i

# Copy the rest of the application code
# COPY . .

# Build the Angular application
# RUN npx ng build -c production 